#!/bin/sh

not() { if "$@" ; then false ; else true ; fi }
q()  { "$@"  >/dev/null }
qe() { "$@" 2>/dev/null }
qq() { "$@"  >/dev/null 2>&1 }

alias c=cat

alias cd..='cd ..'

alias ls='ls --color=auto'
alias l=ls
alias la='ls -a'
alias lA='ls -A'
alias ll='ls -l'
alias lalF='ls -alF'
alias lclr='ls --color=always'

alias j='jobs -l'

alias fg1='fg %1'
alias fg2='fg %2'
alias fg3='fg %3'
alias fg4='fg %4'
alias fg5='fg %5'
alias fg6='fg %6'
fg-() { fg %- }

alias grep='grep --color=auto'
alias g=grep
alias gv='grep -v'
alias gi='grep -i'
alias ge='grep -e'
alias gf='grep -f'

alias md=mkdir
alias mp='mkdir -p'
alias loc=locate

alias ag=apt-get
alias ac=apt-cache

alias e=$EDITOR
alias p=$PAGER
alias v=view

alias emacs-nw='emacs -nw'
alias em=emacs-nw
alias emacs-x=emacs
alias emx=emacs-x

alias del=trash-put
alias open=xdg-open
alias o=open

alias py=py3
alias py3=python3
alias py32=python3.2
alias py2=python2
alias py27=python2.7
alias pyc=pycompile
alias py3c=py3compile
virtualenv.activate() { . ${@:-$PWD}/.virtualenv/bin/activate }

alias sudo='sudo -E '

alias cpr='cp -r'
alias t=tmux

alias psa='ps a'
alias psx='ps x'
alias psax='ps ax'
alias psaux='ps aux'
psg() { ps u | head -n 1 ; ps aux | grep "$*" | grep -v -e 'ps aux' -e grep }

alias kl=kill
alias kl9=kill9
alias kila=killall
alias killa=killall
alias kila9=killall9
alias killa9=killall9
alias kill9='kill -KILL'
alias killall9='killall -KILL'

alias pe='perl -pe'
alias pm=pacman

s() {
    while [ $# != 0 ] ; do
        src="$src"s/`echo -E "$1" | sed -e 's!/!\\/!g'`/"$2"/"$3"\;
        if [ $# -lt 3 ] ; then shift $# ; else shift 3 ; fi
    done
    sed -e "$src"
}

alias uzbl=uzbl-tabbed

alias cmk='cmake .'
alias mk='make -j2'
doxy() { if [ $# = 0 ] ; then doxygen Doxyfile ; else doxygen "$@" ; fi }

alias clrr='clr -r'

firefox-() { tof "$@" firefox -- {} ; }
vim-()     { tof "$@" vim     -- {} ; }
view-()    { tof "$@" view    -- {} ; }

## the prompt is same to the man's one
export LESS='-r -j10 -P \ ?f%f:Standerd Input\.. ?lmline %lm:.?L/%L. ?PB%PB\%:. (press h for help or q to quit)\ \'

fx() { firefox -new-tab "$@" } # why this is a function is to avoid zsh's complementing -new-tab

alias gdb='gdb -quiet'
