#!/bin/sh

alias e=echo
alias en='echo -n'

alias x=exec

alias c=cat

alias cd..='cd ..'

alias ls='ls --color=auto'
alias l=ls
alias la='ls -a'
alias lA='ls -A'
alias ll='ls -l'
alias lalF='ls -alF'

alias jobs='jobs -l'
alias j=jobs

alias fg1='fg %1'
alias fg2='fg %2'
alias fg3='fg %3'
alias fg4='fg %4'
fg-() { fg %- }

alias grep='grep --color=auto'
alias g=grep
if which fgrep >/dev/null ; then alias fgrep='fgrep --color=auto' ; else alias fgrep='grep --fixed-strings' ; fi
if which egrep >/dev/null ; then alias egrep='egrep --color=auto' ; else alias egrep='grep --extended-regexp' ; fi
alias vgrep='grep --invert-match'

alias cpr='cp -r'

alias md=mkdir
alias loc=locate

alias psa='ps a'
alias psx='ps x'
alias psax='ps ax'
alias psaux='ps aux'
psh()  { ps   | head -n 1 } # ps  のheaderを表示
pshu() { ps u | head -n 1 } # ps uのheaderを表示
pst() { pshu ; ps aux | sort -r -n +2 | grep -v 'ps aux' | grep -v grep | head -n 8 } ### CPU 使用率の高い方から8つ
psm() { pshu ; ps aux | sort -r -n +3 | grep -v 'ps aux' | grep -v grep | head -n 8 } ### メモリ占有率の高い方から8つ
psg() { pshu ; ps aux | grep $* | grep -v 'ps aux' | grep -v grep }

alias killa=killall
alias kill9='kill -KILL'
alias killall9='killall -KILL'

alias sudo='sudo -E '

alias ag=apt-get
alias ac=apt-cache

s() {
    x=
    while [ $# != 0 ] ; do
        x="$x"s/`echo -E "$1" | sed -e 's!/!\\/!g'`/"$2"/"$3"\;
        if [ $# -lt 3 ] ; then shift $# ; else shift 3 ; fi
    done
    sed -e "$x"
}

alias del=trash-put
alias open=gnome-open

alias py=python
alias py3=python3
alias py32=python3.2
alias py2=python2
alias py27=python2.7
alias pyc=pycompile
alias py3c=py3compile
virtualenv.activate() { . ${@:-$PWD}/.virtualenv/bin/activate }


alias cmk=cmake
alias mk=make
doxygen() { if [ $# = 0 ] ; then doxygen Doxyfile ; else doxygen "$@" ; fi }

alias rmd=rmdust
alias rmdr='rmdust -r'

via-o2on() {
    o2on_port=8020
    command="$1"
    shift
    if lsof -i:$o2on_port | grep -iq 'o\(py\)\?2on' ; then
        env http_proxy=http://localhost:$o2on_port "$command" "$@"
    else
        "$command" "$@"
    fi
}
2ch-get(){ via-o2on `which -p 2ch-get` "$@" }
2ch-browse(){ via-o2on `which -p 2ch-browse` "$@" }
alias ch=2ch-browse
alias chn='2ch-browse -n'
alias chg='2ch-get -d'
alias chgn='2ch-get -d -n'
alias chgq='2ch-get -q'
alias chf=2ch-format
alias chp=2ch-post
alias chu=2ch-utils

## the prompt is same to the man's one
export LESS='-r -j10 -P \ ?f%f:Standerd Input\.. ?lmline %lm:.?L/%L. ?PB%PB\%:. (press h for help or q to quit)\ \'

fx() { firefox -new-tab "$@" } # -new-tabでzshの補完候補が_filesから`URL to load'になるの回避のためaliasでなくfunction

alias tmp='cd ~/tmp'

vimrc()       { $EDITOR ~/.vimrc }
aliases()     { $EDITOR ~/share/sh/aliases     && . ~/share/sh/aliases }
commands()    { $EDITOR ~/share/sh/commands    && . ~/share/sh/commands }
environment() { $EDITOR ~/share/sh/environment && . ~/share/sh/environment }
zshrc()       { $EDITOR ~/share/zsh/zshrc }
