#!/bin/sh

alias tmp='cd ~/tmp'

vimrc()       { $EDITOR ~/.vimrc }
alias     aliases='$EDITOR ~/share/sh/aliases     && . ~/share/sh/aliases'
alias    commands='$EDITOR ~/share/sh/commands    && . ~/share/sh/commands'
alias environment='$EDITOR ~/share/sh/environment && . ~/share/sh/environment'
zshrc()       { $EDITOR ~/share/zsh/zshrc }

alias fd="env ANSICOLOR=1 fd"
virthualenv.activate() { . ${@:-$PWD}/.virthualenv/bin/activate }

alias talk='ojtalk -vname mei_normal'
alias talk-angry='ojtalk -vname mei_angry'
alias talk-bashful='ojtalk -vname mei_bashful'
alias talk-happy='ojtalk -vname mei_happy'
alias talk-sad='ojtalk -vname mei_sad'

alias notify='notify-send -i terminal'

alias gitignored='git ls-files -o -i --exclude-standard'

gosh() {
    if [ $# -eq 0 ] && which gosh-rl >/dev/null ; then
        gosh-rl "$@" # gosh-rl do not recognize the options
    elif which rlwrap >/dev/null ; then
        rlwrap -pBLUE gosh "$@"
    else
        gosh "$@"
    fi
}

vf() {
    vim -c 'au FileType vimfiler nnoremap <buffer> q :<C-u>quit<CR>' \
        -c 'au FileType vimfiler nnoremap <buffer> Q :<C-u>quit<CR>' \
        -c ':VimFiler -status '"$*"
}

MLOCATE_HOME_DB=$HOME/var/home.mlocate.db
updatedb.home() {
	updatedb --database-root $HOME --output $MLOCATE_HOME_DB --require-visibility 0 $@
}
locate.home() {
	locate --database $MLOCATE_HOME_DB $@
}

'date+%s'() { date +%s "$@" }
'w3m-Ttex/thtml'() { w3m -T text/html "$@" }


## logout for gnome
if ps ax | grep -v grep | grep gnome-session > /dev/null ; then
    alias logout='gnome-session-quit --no-prompt'
fi

# http://qiita.com/mollifier/items/14bbea7503910300b3ba
function zman() {
    PAGER="less -g -s '+/^       "$1"'" man zshall
}


## power management
alias suspend=pm-suspend
alias hibernate=pm-hibernate
alias powersave=pm-powersave
alias suspend-hybrid=pmsuspend-hybrid

apt-add-japanese-repository() {
    # https://ubuntulinux.jp/japanese
    wget -q https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg -O- | apt-key add -
    wget -q https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg -O- | apt-key add -
    wget https://www.ubuntulinux.jp/sources.list.d/oneiric.list -O /etc/apt/sources.list.d/ubuntu-ja.list
    apt-get update
    apt-get upgrade
    apt-get install ubuntu-desktop-ja
}

url_quote() {
    if [ $# = 0 ]
    then echo -n "`cat`"
    else echo -n "$@"
    fi | python3 -c 'import sys, urllib.parse as url ; print(url.quote(sys.stdin.read()))'
}
duckduckgo() { echo http://duckduckgo.com/\?q=`echo $@ | url_quote` }
alias ddg=duckduckgo
wikipedia() {
    lang=en
    case "$1" in
        ja | japan | jp ) lang=ja ; shift ;;
        -- | en | english ) shift ;;
    esac
    echo http://${lang}.wikipedia.org/wiki/`echo $@ | url_quote`
}
alias wikip=wikipedia
alias wkp=wikipedia
google() {
    lang=com
    case "$1" in
        jp | co.jp | japan | ja ) lang=co.jp ; shift ;;
        -- | en | com | english ) shift ;;
    esac
    echo http://www.google.$lang/search\?q=`echo $@ | url_quote`
}
alias ggl=google
bing() { echo http://www.bing.com/search\?q=`echo $@ | url_quote` }
weblio() {
    type=ejje
    case "$1" in
        ejje ) type=$1 ; shift ;;
    esac
    echo http://${type}.weblio.jp/content/`echo $@ | url_quote`\#main
}
hoogle() { echo http://www.haskell.org/hoogle/\?hoogle=`echo $@ | url_quote` }
github() { echo git@github.com:"$1".git }
axfc() {
    case "$#" in
        1 )
            elem=`echo $1 | sed -e 's/_.*//'`
            num=`echo $1 | sed -e 's/.*_//'`
            ;;
        2 )
            elem=$1
            num=$2
            ;;
    esac
    [ -n "$elem" -a -n "`echo "$num" | grep '^[[:digit:]]\+$'`" ] || error "$type"': wrong format argument: '"$*"
    echo http://www1.axfc.net/uploader/"$elem"/so/"$num"
}
nicovideo() {
    num=`echo "$1" | grep '^\(sm\)\?[[:digit:]]\+$'`
    [ "$num" ] || error "$type"': wrong format argument: '"$1"
    echo http://www.nicovideo.jp/watch/sm"$num"
}

bddg() { $BROWSER `duckduckgo "$@"` }
bwkp() { $BROWSER `wikipedia  "$@"` }
bggl() { $BROWSER `google     "$@"` }

hide()   { for i in "$@" ; do mv "$i" "$i".hidden ; done }
unhide() { for i in "$@" ; do mv "$i".hidden "$i" ; done }
