#!/bin/sh


#CURRENT_PROJECT_DIRECTORY=~/work/
work() {
    # you should rewrite frequently
    cd "$CURRENT_PROJECT_DIRECTORY"
    [ -e .virtualenv ] && . .virtualenv/bin/activate
    [ -e .virthualenv ] && . .virthualenv/bin/activate
    echo -e "\e[34m\$ git log\e[0m"
    git --no-pager log --color | head -n16
    echo
    echo -e "\e[34m\$ git diff\e[0m"
    git --no-pager diff --color
    echo
    echo -e "\e[34m\$ ls\e[0m"
    ls
}

alias fd="env ANSICOLOR=1 fd"
virthualenv.activate() { . ${@:-$PWD}/.virthualenv/bin/activate }

alias talk='ojtalk -vname mei_normal'
alias talk-angry='ojtalk -vname mei_angry'
alias talk-bashful='ojtalk -vname mei_bashful'
alias talk-happy='ojtalk -vname mei_happy'
alias talk-sad='ojtalk -vname mei_sad'

alias notify='notify-send -i terminal'

alias gitignored='git ls-files -o -i --exclude-standard'

gosh() {
    if [ $# -eq 0 ] && which gosh-rl >/dev/null ; then
        gosh-rl "$@" # gosh-rl do not recognize the options
    elif which rlwrap >/dev/null ; then
        rlwrap -pBLUE gosh "$@"
    else
        gosh "$@"
    fi
}

vf() {
    vim -c 'au FileType vimfiler nnoremap <buffer> q :<C-u>quit<CR>' \
        -c 'au FileType vimfiler nnoremap <buffer> Q :<C-u>quit<CR>' \
        -c ':VimFiler -status '"$*"
}

grep_unite() {
    grep "$@" ~/.vim/bundle/unite.vim/**/*.vim
}

grep_vimfiler() {
    grep "$@" ~/.vim/bundle/vimfiler/**/*.vim
}


MLOCATE_HOME_DB=$HOME/var/home.mlocate.db
updatedb.home() {
	updatedb --database-root $HOME --output $MLOCATE_HOME_DB --require-visibility 0 $@
}
locate.home() {
	locate --database $MLOCATE_HOME_DB $@
}

'date+%s'() { date +%s "$@" }
'w3m-Ttex/thtml'() { w3m -T text/html "$@" }


## logout for gnome
if ps ax | grep -v grep | grep gnome-session > /dev/null ; then
    alias logout='gnome-session-quit --no-prompt'
fi


## power management
alias suspend=pm-suspend
alias hibernate=pm-hibernate
alias powersave=pm-powersave
alias suspend-hybrid=pmsuspend-hybrid


apt-add-japanese-repository() {
    # https://ubuntulinux.jp/japanese
    wget -q https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg -O- | apt-key add -
    wget -q https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg -O- | apt-key add -
    wget https://www.ubuntulinux.jp/sources.list.d/oneiric.list -O /etc/apt/sources.list.d/ubuntu-ja.list
    apt-get update
    apt-get upgrade
    apt-get install ubuntu-desktop-ja
}
