#!/bin/sh

export LANG=en_US.UTF-8

export EDITOR=vim
export VISUAL=vim
export PAGER=less


export PATH="$HOME/.cabal/bin":"$PATH"
export PATH="$HOME/bin":"$PATH"
export PATH="$HOME/local/bin":"$PATH"
export PATH="$HOME/var/bin":"$PATH"
export PATH="$HOME/local/lib/2ch-tools/bin":"$PATH"

export PATH="$HOME/.rbenv/bin":"$PATH"
if which rbenv > /dev/null ; then
    eval "$(rbenv init -)"
fi

export PATH="$(echo $PATH | trimpath)"
