#!/usr/bin/zsh

HISTSIZE=100000000 # 保存する量
SAVEHIST=100000000
HISTFILE=$HOME/var/history/zsh # 保存先の指定(必須,しなければ履歴は遺棄)

bindkey -e # keybinding is emacs-like
setopt append_history # 複数の zsh を同時に使う時など history ファイルに上書きせず追加する
setopt hist_ignore_space # スペースから始まる行は追加しない
setopt hist_ignore_all_dups # 同じコマンドラインはヒストリに追加しない
setopt share_history # シェルのプロセスごとに履歴を共有
setopt list_packed # 補完候補リストを詰めて表示
setopt print_eight_bit # 補完候補リストの日本語を適正表示
setopt auto_param_keys # カッコの対応などを自動的に補完する
setopt auto_param_slash # ディレクトリ名の補完で末尾の / を自動的に付加し、次の補完に備える
setopt auto_remove_slash # 最後がディレクトリ名で終わっている場合末尾の / を自動的に取り除く
setopt equals # =command を command のパス名に展開する
setopt correct # コマンドのスペルチェックをする
setopt brace_ccl # {a-c} を a b c に展開する機能を使えるようにする
setopt auto_list # 補完候補が複数ある時に、一覧表示する
setopt list_types # auto_list の補完候補一覧で、ls -F のようにファイルの種別をマーク表示
setopt auto_menu # 補完キー（Tab, Ctrl+I) を連打するだけで順に補完候補を自動で補完する
setopt magic_equal_subst # コマンドラインの引数で --prefix=/usr などの = 以降でも補完できる
setopt print_exit_value # 戻り値が 0 以外の場合終了コードを表示する
setopt NO_beep # ビープ音を鳴らさないようにする
setopt short_loops # for, repeat, select, if, function などで簡略文法が使えるようになる
setopt autopushd # cd -[tab] でpushd
REPORTTIME=60 # CPUを8秒以上使った時は time を表示
TIMEFMT="\
    The name of this job.             :%J
    CPU seconds spent in user mode.   :%U
    CPU seconds spent in kernel mode. :%S
    Elapsed time in seconds.          :%E
    The  CPU percentage.              :%P"


source ~/share/sh/environment
source ~/share/sh/aliases
source ~/share/sh/commands
source ~/share/zsh/completion.zsh
source ~/share/zsh/auto-fu.zsh
source ~/share/zsh/antigen.zsh


# 初期位置は~/tmp
if [ -z "$ZSH_MOVED_TO_TMP" ] ; then
    export ZSH_MOVED_TO_TMP=t
    [ -e ~/tmp ] && [ `pwd` = `cd && pwd` ] && cd ~/tmp
fi
